/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.negocio.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import com.negocio.model.JsonApiBodyResponseErrors;
import com.negocio.model.JsonApiBodyResponseSuccessNegocio;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-08-17T19:49:20.948Z")

@Api(value = "eliminar", description = "the eliminar API")
public interface EliminarApi {

    @ApiOperation(value = "Eliminar negocio", nickname = "eliminarIdnegocioDelete", notes = "Eliminar negocio por id de negocio", response = JsonApiBodyResponseSuccessNegocio.class, tags={ "negocios", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = JsonApiBodyResponseSuccessNegocio.class),
        @ApiResponse(code = 404, message = "Negocio no encontrado", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/eliminar/{idnegocio}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<JsonApiBodyResponseSuccessNegocio> eliminarIdnegocioDelete(@ApiParam(value = "ID del negocio",required=true) @PathVariable("idnegocio") String idnegocio);

}
